server:
  port: 8180

spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=online_shop_system
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    platform: postgres
    initialization-mode: always

  data:
    mongodb:
      host: localhost
      port: 27017
      database: online_shopping_system

  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
